stages:
  - build
  - test
  - release

variables:
  # DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DVOTE_NODE_BUILD_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  DVOTE_NODE_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}:latest
  DOCKER_CLI_EXPERIMENTAL: enabled
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  GOPATH: ${CI_PROJECT_DIR}/.cache/gopath # to cache Go module downloads
  GOCACHE: ${CI_PROJECT_DIR}/.cache/gocache # to cache Go build archives
  GOFLAGS: -mod=readonly

  TESTSUITE_ORACLE_KEY: 6aae1d165dd9776c580b8fdaf8622e39c5f943c715e20690080bbfce2c760223
  TESTSUITE_ELECTION_SIZE: 1000

cache:
  key: ${CI_JOB_NAME} # separate caches by job, but not by branch
  paths:
    - .cache/

go-test:
  image: golang:1.15.2
  stage: test
  tags:
    - vocdoni
  script:
    # we run vet in another step
    - go test -vet=off -timeout=1m ./...
    # -race can easily make the crypto stuff 10x slower
    - go test -vet=off -timeout=15m -race ./...
  only:
    - merge_requests
    - branches

go-analyze:
  image: golang:1.15.2
  stage: test
  tags:
    - vocdoni
  script:
    - diff -u <(echo -n) <(gofmt -s -d $(git ls-files '*.go'))
    - go vet ./...
    - curl -L https://github.com/dominikh/go-tools/releases/download/2020.1.5/staticcheck_linux_amd64.tar.gz | tar -xzf -
    - ./staticcheck/staticcheck ./...
  only:
    - merge_requests
    - branches

compose-test:
  image: docker/compose:1.25.5
  stage: test
  tags:
    - vocdoni
  script:
    # Avoid compose project collisions in parallel runs
    - export COMPOSE_PROJECT_NAME=${RANDOM}${RANDOM}_testsuite
    - export TESTSUITE_BUILD_TAG=${CI_COMMIT_SHA::10}
    - export COMPOSE_HOST_PATH=${CI_PROJECT_DIR}/dockerfiles/testsuite
    - export COMPOSE_DVOTE_PORT_MAPPING="9090" # Will use a random available port mapping
    - cd dockerfiles/testsuite
    - docker-compose build
    - sh start_test.sh
  only:
    - merge_requests
    - master

docker-release:
  image: docker:stable
  services:
    - docker:dind
  stage: release
  tags:
    - vocdoni
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t ${DVOTE_NODE_BUILD_IMAGE} .
    - docker tag ${DVOTE_NODE_BUILD_IMAGE} ${DVOTE_NODE_RELEASE_IMAGE}
    #- docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker push ${DVOTE_NODE_BUILD_IMAGE}
    - docker push ${DVOTE_NODE_RELEASE_IMAGE}
  only:
    - master
    - /^release-.*$/
    - stage
